DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS session;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    games INTEGER NOT NULL,
    wins INTEGER NOT NULL,
    cur_winstreak INTEGER NOT NULL,
    long_winstreak INTEGER NOT NULL
);

CREATE TABLE session (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token TEXT UNIQUE NOT NULL,
    guesses INTEGER NOT NULL,
    game_id INTEGER NOT NULL,
    win INTEGER NOT NULL
);